move generalization calculations to web worker
2gis/general pull request #1
Opened 2017-04-03 12:45 UTC by RLRR

2017-04-04 03:14 UTC, Trufi requested changes
* Я добавил команду `npm run lint` в мастер, поправь плз синтаксис
* С учетом появления воркера, не лучше ли сделать `generalize` не функцией, а классом? Мне, кажется,  что нужно будет добавить что-то вроде метода `clear`, который бы очищал всю очередь

2017-04-04 03:14 UTC, Trufi commented on src/Generalize.ts
> +import { BBox, PriorityGroup, Atlas, Marker, WorkerMessage, Job } from './types';
Давай в столбик сделаем?

2017-04-04 03:14 UTC, Trufi commented on src/Generalize.ts
> +        sprites: atlas.sprites,
Атлас нет смысла тоже в массив паковать? Может быть достаточно много спрайтов

2017-04-04 03:14 UTC, Trufi commented on src/markerArray.ts
> +    'positionY',
А `positionX` и `positionY` где-нибудь в воркере используются?

2017-04-04 09:45 UTC, RLRR commented on src/Generalize.ts
> +import { BBox, PriorityGroup, Atlas, Marker, WorkerMessage, Job } from './types';
done

2017-04-04 09:46 UTC, RLRR commented on src/markerArray.ts
> +    'positionY',
Точно, не используются, убрал

2017-04-04 09:47 UTC, RLRR commented on src/Generalize.ts
> +        sprites: atlas.sprites,
Думаю, если их будет порядка нескольких десятков, то можно забить)

2017-04-04 09:56 UTC, Trufi commented on demo/index.ts
> +        general.generalize(bounds, retinaFactor, priorityGroups, atlas, markers).then(() => {
😆

2017-04-04 09:58 UTC, Trufi approved these changes

2017-04-04 10:55 UTC, egoroof commented on demo/index.ts
> +            console.timeEnd('gen');
консоль потом выпилите?

2017-04-04 10:55 UTC, egoroof commented on src/General.ts
> +const prevGroupIndexOffset = offsets['prevGroupIndex'];
а зачем эти ссылки? почему не использовать `offsets['что-то']` в коде вместо `что-тоOffset `? а ещё лучше через точку - например `offsets.prevGroupIndex`

2017-04-04 10:55 UTC, egoroof commented on src/worker.ts
> +const pixelPositionYOffset = offsets['pixelPositionY'];
тут тоже зачем ссылки создавать?

2017-04-04 10:58 UTC, RLRR commented on demo/index.ts
> +            console.timeEnd('gen');
Выпилим)

2017-04-04 10:59 UTC, RLRR commented on src/General.ts
> +const prevGroupIndexOffset = offsets['prevGroupIndex'];
Это супер-микро-оптимизация, чтобы в циклах на каждый маркер не делать получение элемента из объекта (`offsets['prevGroupIndex']`)

2017-04-04 10:59 UTC, RLRR commented on src/General.ts
> +const prevGroupIndexOffset = offsets['prevGroupIndex'];
А на точку кстати можно переделать

2017-04-04 11:03 UTC, egoroof commented on src/General.ts
> +const prevGroupIndexOffset = offsets['prevGroupIndex'];
в таком случае больше памяти потребуется..

2017-04-04 11:04 UTC, egoroof approved these changes

2017-04-04 11:08 UTC, egoroof commented on src/General.ts
> +const prevGroupIndexOffset = offsets['prevGroupIndex'];
а есть тесты производительности по получению элемента из объекта vs использование ссылок?

2017-04-04 11:13 UTC, RLRR commented on src/General.ts
> +const prevGroupIndexOffset = offsets['prevGroupIndex'];
Да, но мы как-то традиционно всегда намного больше паримся насчёт скорости, чем памяти; тем более, тут всего 5 намберов)

...тестов нет, но на досуге сделаю

2017-04-04 11:18 UTC, merged

2017-04-04 11:20 UTC, Trufi commented on src/General.ts
> +const prevGroupIndexOffset = offsets['prevGroupIndex'];
Кажется, что такой тест сложно будет сделать легитимным. Предполагаю, что большой разницы в производительности не будет.

2017-04-04 11:27 UTC, egoroof commented on src/General.ts
> +const prevGroupIndexOffset = offsets['prevGroupIndex'];
 я тоже так думаю, что разницы не будет - это ведь скорее всего оптимизируют js движки

2017-04-04 16:00 UTC, lastw commented on src/General.ts
> +const prevGroupIndexOffset = offsets['prevGroupIndex'];
![image](https://cloud.githubusercontent.com/assets/1522798/24666416/75b1b35c-198a-11e7-8e7c-318879193c03.png)

2017-04-04 16:55 UTC, RLRR commented on src/General.ts
> +const prevGroupIndexOffset = offsets['prevGroupIndex'];
В общем, я на всякий случай составил тестик, и, думаю, можно с чистой совестью убирать эти переменные :D
![image](https://cloud.githubusercontent.com/assets/4540062/24668709/0f9bbc5e-1992-11e7-9676-65ba8f024a76.png)
Завтра сделаю ПР

2017-04-04 17:17 UTC, egoroof commented on src/General.ts
> +const prevGroupIndexOffset = offsets['prevGroupIndex'];
> Программисты тратят огромное количество времени, размышляя и беспокоясь о некритичных местах кода, и пытаются оптимизировать их, что исключительно негативно сказывается на последующей отладке и поддержке. Мы должны вообще забыть об оптимизации в, скажем, 97% случаев. Поспешная оптимизация является корнем всех зол. И, напротив, мы должны уделить все внимание оставшимся 3%.
— Дональд Кнут

http://optimization.guide/

2017-04-05 06:50 UTC, RLRR commented on src/General.ts
> +const prevGroupIndexOffset = offsets['prevGroupIndex'];
![optimization](https://cloud.githubusercontent.com/assets/4540062/24693243/d931b63a-1a06-11e7-9efa-dec25a14711c.png)

2017-04-05 06:51 UTC, RLRR commented on src/General.ts
> +const prevGroupIndexOffset = offsets['prevGroupIndex'];
https://github.com/2gis/general/pull/4