Rework hysteresis
2gis/general pull request #26
Opened 2019-01-04 07:02 UTC by RLRR

### Что сделано
1. У типа `Marker` убрано поле `prevGroupIndex`. Поле `iconIndex` сделано обязательным.
2. Видимость маркера на экране определяется по значению поля `iconIndex`, которое остаётся с прошлой генерализации.
3. Генерализация работает теперь в два прогона: на первом обрабатываются видимые в данный момент маркеры, на втором — невидимые.
4. На втором прогоне к `collideBBox` каждого маркера добавляется два пикселя с каждой стороны.
5. В остальном логика никак изменилась.

### Результаты
* 👍  Упростился интерфейс библиотеки: теперь нет необходимости следить за полем `prevGroupIndex` и сбрасывать его значение в нужные моменты, вся логика гистерезиса теперь спрятана внутри либы. К тому же, теперь нет необходимости проверять `iconIndex` на `undefined`.
* 👍 Значительно улучшилась стабильность генерализации при зуме.
* 👍 Немного улучшилась стабильность генерализации при повороте.
* 👎 Стабильность генерализации при драге незначительно ухудшилась.

Идеальной стабильности, к сожалению, достичь не удалось: при любых взаимодействиях с картой периодически наблюдаются мерцания маркеров. Однако, в совокупности картина стала намного лучше.

2019-01-04 07:12 UTC, osvodef commented on src/worker/generalize.ts
> +        if (!sprite) {
Кто-нибудь знает, что это за проверка? Коммент не помогает :(

2019-01-10 06:42 UTC, Trufi requested changes

2019-01-10 06:42 UTC, Trufi commented on src/worker/generalize.ts
> +        mode === GeneralizationMode.Appear ? 2 : 0,
Откуда берется 2? Нужен коммент

2019-01-10 06:42 UTC, Trufi commented on src/worker/generalize.ts
> +    // Циклы запускаются два раза: первый прогон — для маркеров, которые в данный момент видны на экране
Я бы заменил "в данный момент видны" на "были видны". С моей точки зрения мы обрабатываем все маркеры, которые попали во вьюпорт, т.е. видны в данный момент.

2019-01-10 06:42 UTC, Trufi commented on src/worker/generalize.ts
> +        if (!sprite) {
Видимо, добавлено, чтобы не ловить эксепшен, если кто-то случайно укажет кривые `iconIndex` в группах

2019-01-15 07:13 UTC, egoroof commented on tsconfig.json
> +        "skipLibCheck": true
а зачем skipLibCheck включил - вроде ведь новых зависимостей не добавлял

2019-01-15 07:50 UTC, RLRR commented on tsconfig.json
> +        "skipLibCheck": true
Не знаю, но без него сейчас не собирается

2019-01-16 06:59 UTC, RLRR commented on src/worker/generalize.ts
> +    // Циклы запускаются два раза: первый прогон — для маркеров, которые в данный момент видны на экране
Поправил

2019-01-16 06:59 UTC, RLRR commented on src/worker/generalize.ts
> +        mode === GeneralizationMode.Appear ? 2 : 0,
Добавил

2019-01-18 05:54 UTC, Trufi requested changes

2019-01-18 05:54 UTC, Trufi commented on src/worker/generalize.ts
> +    const appearMargin = 2;
Какой смысл использовать `appearMargin`, если в отличие от карты, тут у нас и так используются два разных отступа: при проверке может ли маркер встать, мы используем его `safeZone`, но у уже вставших маркеров мы используем `margin`.

2019-01-18 05:54 UTC, Trufi commented on src/worker/generalize.ts
> +    // Это поведение аналогично логике лейблинга в 3D-карте
Коммент вообще не объясняет смысл происходящего. А почему в карте мы прибавляем 2 пикселя?

2019-01-21 06:25 UTC, osvodef commented on src/worker/generalize.ts
> +    const appearMargin = 2;
Да согласен, пользы тут мало от этой логики, так что убрал её. Сейчас ещё на глаз проверил с ней и без неё — разницы нет.

2019-01-21 06:25 UTC, osvodef commented on src/worker/generalize.ts
> +        if (!sprite) {
Написал подробный коммент

2019-01-21 06:29 UTC, Trufi approved these changes

2019-01-21 07:17 UTC, egoroof approved these changes

2019-01-21 08:01 UTC, merged