implement marker label generalization
2gis/general pull request #29
Opened 2019-07-23 12:33 UTC by osvodef

Реализовал генерализацию подписей вместе с маркерами. Подпись маркера приходит в опциональном поле `htmlMarker`. Для подписей работает гистерезис, приоритеты расставляются в следующем порядке:
1. Отображаемые маркеры
2. Отображаемые подписи
3. Скрытые маркеры
4. Скрытые подписи

Для генерализации пришлось добавить новую плоскость `noMarginPlane`, так как обычную `plane` маркеры помещаются с маржинами, что мешает размещать подпись.

2019-07-24 02:54 UTC, Trufi requested changes

2019-07-24 02:54 UTC, Trufi commented on README.md
> +- `htmlLabel?: Label` — опциональная подпись маркера. Подписи генерализуются аналогично маркерам. У подписей при генерализации меньший приоритет, чем у маркеров. Другими словами, сначала генерализуют
Давай уберем тут слово `html`? Генерал не знает таких конкретных вещей, как "подпись нарисованная c помощью html", его задача — только генерализация.

2019-07-24 02:55 UTC, Trufi commented
Добавился новый функционал, уверен, что ничего не надо покрывать дополнительным тестами?

2019-07-24 02:57 UTC, Trufi commented
Что насчет производительности? Изменилось что-то?

2019-07-24 10:43 UTC, osvodef commented on README.md
> +- `htmlLabel?: Label` — опциональная подпись маркера. Подписи генерализуются аналогично маркерам. У подписей при генерализации меньший приоритет, чем у маркеров. Другими словами, сначала генерализуют
В таком случае его придётся переименовать везде, так как оно используется и онлайном, и Rarity, и Джакартой

2019-07-24 11:35 UTC, Trufi commented on README.md
> +- `htmlLabel?: Label` — опциональная подпись маркера. Подписи генерализуются аналогично маркерам. У подписей при генерализации меньший приоритет, чем у маркеров. Другими словами, сначала генерализуют
😥

2019-07-29 06:53 UTC, osvodef commented
> Добавился новый функционал, уверен, что ничего не надо покрывать дополнительным тестами?
Покрыл тестами генерализацию лейблов, заодно покрыл ими и гистерезис

2019-07-29 07:13 UTC, osvodef commented
> Что насчет производительности? Изменилось что-то?

На глаз ничего не изменилось. По выводу в консоль в демке также разницы не заметил. Правда, в демке в данных нет подписей, так что говорит это только о том, что добавление новой плоскости не ухудшило на производительность.

Генерализация одной подписи должна стоить значительно меньше, чем генерализация одного маркера, так как она происходит только в одной плоскости. Можно заморочиться, добавить в данные маркеров в демке подписи и замерить производительность, но так как подписи всё равно не будут отображаться, не вижу большого смысла это делать.

2019-07-29 08:14 UTC, Trufi approved these changes

2019-07-29 09:28 UTC, Trufi commented on src/worker/generalize.ts
> +    // 3. Неприоритетные маркеры, видимые на экране, затем их подписи
А почему видимые неприоритетные маркеры генерализуются позже приоритетных невидимых? Разве это не добавит мелькания в картинку?

2019-07-29 11:12 UTC, alxart approved these changes

2019-07-30 07:42 UTC, osvodef commented on src/worker/generalize.ts
> +    // 3. Неприоритетные маркеры, видимые на экране, затем их подписи
Я сначала сделал вариант, когда, видимые неприоритетные генерализовались раньше. Оказалось, что подписям приоритетных маркеров всё равно было очень сложно разместиться, особенно если плавно призумливать карту.

В этом варианте ухудшения стабильности я не заметил, а приоритетным маркерам и их подписям при этом отдаётся наибольшее внимание.

2019-08-01 03:48 UTC, merged