Text in a separate plane
2gis/general pull request #35
Opened 2020-01-13 04:22 UTC by egoroof

2020-01-14 05:01 UTC, egoroof commented on test/generalize.spec.ts
> -                'Подпись второго маркера перекрыта подписью первого маркера, ' +
удалил это тест т.к. он выглядит невалидным - две подписи пересекаются, но обе выживают (в моём ПРе они перестали выживать - ожидаемо)

2020-01-14 08:00 UTC, Trufi commented
Я правильно понял, что теперь маркер НЕ РД, может находиться под подписью РД?

2020-01-14 09:02 UTC, egoroof commented
> Я правильно понял, что теперь маркер НЕ РД, может находиться под подписью РД?

да

2020-01-14 10:22 UTC, Trufi commented
Так цель же была другой — чтобы только РД маркеры могли находиться под подписью другого РД, а с другими маркерами это не должно работать.

2020-01-14 13:13 UTC, osvodef requested changes

2020-01-14 13:13 UTC, osvodef commented on src/worker/generalize.ts
> +    // С помощью этой плоскости проверяется попадание маркеров с safeZone и вставляется они с margin
вставляется → вставляются, и после `safeZone` нужна запятая

2020-01-15 06:24 UTC, egoroof commented
> а с другими маркерами это не должно работать.

в задаче про это ничо не было написано

сейчас работает как в мобилке + в слэке Сырков и Кочанов это решили так оставить

2020-01-15 06:26 UTC, egoroof commented on src/worker/generalize.ts
> +    // С помощью этой плоскости проверяется попадание маркеров с safeZone и вставляется они с margin
пофиксил

2020-01-15 07:57 UTC, Trufi approved these changes

2020-01-16 05:57 UTC, osvodef approved these changes
По коду прям стало лучше, чем было :+1:

2020-01-16 06:37 UTC, merged